### ISSUE TITLE
Features checklist

### ISSUE THREAD

**Issue by tfuxu** [gradienceisahack/gradienceisahack.github.io#3]
A list of things to add in future:
- [ ] A note about not making theming issues in other projects, if previously themed with Gradience,
- [ ] Explain Gradience purpose,
- [ ] Add _shameless plug_ section, just something like a second section in [usegradience](https://usegradience.github.io) that tells what Gradience is, with a single button to download site, we could maybe place it at the end of the site

This list is mostly compiled from things mentioned in discussion on our Matrix server.

**Comment by daudix** [comment]
Not sure about _shameless plug_ as there is usegradience

**Comment by tfuxu** [comment]
I know, but those websites are essentially a promotional materials for Gradience, so we should put in them at least a small section at the end with a list of things Gradience can do, and a download button. That way if a user encounters any of those sites, and he's interested in Gradience after reading them, he can simply click a single button, instead of looking how to download Gradience on the internet.

**Comment by daudix** [comment]
Hmm, sounds good!

**Comment by 0xMRTT** [comment]
Yes 👍
